package service

import "LightningOnOmni/config/chainhash"

//type: -351 (commitment_tx)
type Commitment_tx struct {
	Id int `storm:"id,increment" `
	//the global channel id.
	Channel_id chainhash.Hash `json:"channel_id"`
	//the id of the Omni asset
	Property_id int `json:"property_id"`
	//amount of the payment
	Amount float64 `json:"amount"`
	//private key of Alice2, encrypted by Bob's public key
	Encrpted_Alice2_private_key chainhash.Hash `json:"encrpted_alice_2_private_key"`
}

//type: -352 (commitment_tx_signed)
type Commitment_tx_signed struct {
	Id int `storm:"id,increment" `

	//the global channel id.
	Channel_id chainhash.Hash `json:"channel_id"`
	//the id of the Omni asset.
	Property_id int `json:"property_id"`
	//amount of the payment.
	Amount float64 `json:"amount"`
	//signature of Bob.
	Receiver_signature chainhash.Signauture `json:"receiver_signature"`
}

//type: -353 (get_balance_request)
type Get_balance_request struct {
	Id int `storm:"id,increment" `

	//the global channel id.
	Channel_id chainhash.Hash `json:"channel_id"`
	//the p2sh address generated in funding_signed message.
	P2sh_address chainhash.Hash `json:"p_2_sh_address"`
	// the channel owner, Alice or Bob, can query the balance.
	Who chainhash.Hash `json:"who"`
	//the signature of Alice or Bob
	Signature chainhash.Signauture `json:"signature"`
}

//type: -354 (get_balance_respond)
type Get_balance_respond struct {
	Id int `storm:"id,increment" `
	//the global channel id.
	Channel_id chainhash.Hash `json:"channel_id"`
	//the asset id generated by Omnilayer protocol.
	Property_id int `json:"property_id"`
	//the name of the asset.
	Name string `json:"name"`
	//balance in this channel
	Balance float64 `json:"balance"`
	//currently not in use
	Reserved float64 `json:"reserved"`
	//currently not in use
	Frozen float64 `json:"frozen"`
}
