package service

import "LightningOnOmni/config/chainhash"

//type: -351 (commitment_tx)
type Commitment_tx struct {
	//the global channel id.
	Channel_id chainhash.Hash
	//the id of the Omni asset
	Property_id int
	//amount of the payment
	Amount float64
	//private key of Alice2, encrypted by Bob's public key
	Encrpted_Alice2_private_key chainhash.Hash
}

//type: -352 (commitment_tx_signed)
type Commitment_tx_signed struct {
	//the global channel id.
	Channel_id chainhash.Hash
	//the id of the Omni asset.
	Property_id int
	//amount of the payment.
	Amount float64
	//signature of Bob.
	Receiver_signature chainhash.Signauture
}

//type: -353 (get_balance_request)
type Get_balance_request struct {
	//the global channel id.
	Channel_id chainhash.Hash
	//the p2sh address generated in funding_signed message.
	P2sh_address chainhash.Hash
	// the channel owner, Alice or Bob, can query the balance.
	Who chainhash.Hash
	//the signature of Alice or Bob
	Signature chainhash.Signauture
}

//type: -354 (get_balance_respond)
type Get_balance_respond struct {
	//the global channel id.
	Channel_id chainhash.Hash
	//the asset id generated by Omnilayer protocol.
	Property_id int
	//the name of the asset.
	Name string
	//balance in this channel
	Balance float64
	//currently not in use
	Reserved float64
	//currently not in use
	Frozen float64
}
