package enum

const (
	Tips_common_wrong                         = "Error "
	Tips_common_empty                         = "Empty "
	Tips_common_savedBefore                   = "This record/data already exists in the database."
	Tips_common_invilidMsgHash                = "This message according to the msgHash has already been processed."
	Tips_common_notFound                      = "Not found in the database"
	Tips_common_failToSign                    = "Failed to sign %s "
	Tips_common_userNotOnline                 = "User is not online"
	Tips_common_userNotInTx                   = "The message receiver is not the participant of current transaction."
	Tips_common_notExistProperty              = "Omni asset %d can not be found via omnicore."
	Tips_common_amountMustGreater             = "The amount in transaction must be more than %.8f"
	Tips_common_failToParseInputsFromUnsendTx = "Fail to extract information from the input of the unbroadcast transaction."
	Tips_common_wrongAddressOfRD              = "Wrong output address of RD(revockable delivery) transaction."
	Tips_common_errorObdPeerId                = "There is no connection with obd node %s, please verify the node address and try to connect again, or call protocol message -102003"
	Tips_common_newTxMsg                      = "There is one pending transaction in the channel, please finish it before proceeding another"

	Tips_user_nilUser          = "user is null, please login first."
	Tips_user_notExistOrOnline = "%s does not exist, or is offline."

	Tips_channel_notFoundChannelInCreate               = "Channel msg: can not find the channel currently being created via temporary channel id: "
	Tips_channel_notThePeerIdB                         = "Channel msg: you are not the channel acceptor."
	Tips_channel_changePubkeyForChannel                = "Channel msg: please use another pubkey, because this pubkey has already been used in creating multi-sig channel address."
	Tips_channel_wrongLatestCommitmentTxState          = "Channel msg: the status of the latest commitment transaction doesn't meet the requirement."
	Tips_channel_notFoundLatestCommitmentTx            = "Channel msg: can not find the lastest commitment transaction."
	Tips_channel_LatestCommitmentTxNotInReadySendState = "Channel msg: current commitment transaction is not ready to be broadcast."
	Tips_channel_cannotDelChannel                      = "Channel msg: Finished funding channel, and it can not be deleted."

	Tips_funding_notFoundChannelByTempId         = "Can not find the channel via temporary channel id: "
	Tips_funding_notFoundChannelByChannelId      = "Can not find the channel via channel id: "
	Tips_funding_notFundBtcState                 = "This channel is not ready to fund bitcoins."
	Tips_funding_notFundAssetState               = "This channel is not ready to fund assets."
	Tips_funding_failDecodeRawTransaction        = "Failed in decoding RawTransaction."
	Tips_funding_needChangeFundTx                = "此充值交易的已经被使用过了，请重新构建一个"
	Tips_funding_notEnoughBtcFundingTime         = "Please fund bitcoin three times. This requirement will be deprecated after omnicore supports sendMany."
	Tips_funding_enoughBtcFundingTime            = "You have funded bitcoins three times. Now you are ready to move forward to fund assets."
	Tips_funding_btcAmountMustGreater            = "Need more bitcoins, which is required to be more than: "
	Tips_funding_btcTxBeenSend                   = "This transaction has already been broadcast."
	Tips_funding_fundTxIsRunning                 = "Please wait till the ongoing bitcoin funding process is finished."
	Tips_funding_notFoundFundBtcTx               = "Can not find the bitcoin funding transaction."
	Tips_funding_notFoundFundAssetTx             = "Can not find the asset funding transaction."
	Tips_funding_notFoundVin                     = "Can not find vin in transaction hex."
	Tips_funding_notFoundVout                    = "Can not find vout in transaction hex."
	Tips_funding_wrongBtcHexVin                  = "Data error of vin in transaction hex："
	Tips_funding_wrongFunderAddressFromBtcHex    = "Input address of current bitcoin funding transaction is not the funder's address(funderAddress) in creading this channel."
	Tips_funding_wrongChannelAddressFromBtcHex   = "Target address of current bitcoin funding transaction is not the multi-sig address in creating this channel."
	Tips_funding_wrongFunderAddressFromAssetHex  = "Input address %s of current asset funding transaction is not the funder's address(funderAddress) in creading this channel."
	Tips_funding_wrongChannelAddressFromAssetHex = "arget address %s of current asset funding transaction is not the multi-sig address %s in creating this channel."

	Tips_rsmc_broadcastedChannel     = "The amount of assets in this channel has been changed. Possiblly someone closed this channel, or broadcasted a commitment transaction."
	Tips_rsmc_notTargetUser          = "You are not authorized to process the message."
	Tips_rsmc_errorCommitmentTxType  = "The transaction type does not match the latest commitment transaction. There may be some other pending processes."
	Tips_rsmc_errorCommitmentTxState = "The latest commitment transaction state does not match the requirement: "
	Tips_rsmc_notEnoughBalance       = "Balance is not enough"
	Tips_rsmc_wrongPrivateKeyForLast = "Input private key %s does not match the pubkey %s of previous transaction."
	Tips_rsmc_wrongChannelPrivateKey = "Input channel private key %s does not match the pubKey %s in creating the channel."
	Tips_rsmc_notSameValueWhenCreate = "Input %s is not the same to the one %s used in creating."
	Tips_rsmc_notPairPrivAndPubKey   = "%s and %s are not a legitimate pub/prive key pair."
	Tips_rsmc_notDoItAgain           = "Current transaction is finished, do not process it again."
	Tips_rsmc_failToCreate           = "Failed in creating %s"
	Tips_rsmc_failToGetInput         = "Failed in get vin data for signing %s."

	Tips_htlc_expiryTimeAfterNow         = "%s must be later than current time."
	Tips_htlc_noPrivatePath              = "Can not find an available private channel."
	Tips_htlc_noChanneFromRountingPacket = "Can not find available channel in routing_packet."
	Tips_htlc_notTheHltcSender           = "The target user is not the payer of this HTLC."
	Tips_htlc_wrongRForH                 = "The input R does not match the H which is used as a locker of this HTLC."
	Tips_htlc_failToGetBlockHeight       = "Failed to get heigh of blocks, please try again later."
	Tips_htlc_timeOut                    = "The transaction expired. Don't send R again."
	Tips_htlc_wrongChannelState          = "This channel is processing an HTLC (channel state: %d) now, and is not available for other requests, which need the channel state to be: %d"
)
