package enum

const (
	Tips_common_wrong                         = "错误的 "
	Tips_common_empty                         = "空的 "
	Tips_common_savedBefore                   = "在数据库已经存在了"
	Tips_common_invilidMsgHash                = "此条msgHash对应的消息已经处理过了"
	Tips_common_notFound                      = "未能在数据库中找到"
	Tips_common_failToSign                    = "对 %s 签名失败"
	Tips_common_userNotOnline                 = "用户不在线"
	Tips_common_userNotInTx                   = "消息接收者不是当前交易的交易方"
	Tips_common_notExistProperty              = "id为%d的omni资产未能在omnicore找到"
	Tips_common_amountMustGreater             = "交易数量必须大于%.8f"
	Tips_common_failToParseInputsFromUnsendTx = "从未广播的交易解析inputs失败"
	Tips_common_wrongAddressOfRD              = "错误的rd的output地址"

	Tips_channel_notFoundChannelInCreate               = "未能通过临时通道id找到处于创建状态的通道: "
	Tips_channel_notThePeerIdB                         = "你不是通道创建的接收方 "
	Tips_channel_changePubkeyForChannel                = "因为生成的通道多钱地址已经用过了，请换一个pubkey"
	Tips_channel_wrongLatestCommitmentTxState          = "最新承诺交易的当前状态不满足要求"
	Tips_channel_notFoundLatestCommitmentTx            = "没有找到最新的承诺交易"
	Tips_channel_LatestCommitmentTxNotInReadySendState = "当前承诺交易的状态不是可以广播的状态"
	Tips_channel_cannotDelChannel                      = "通道资产充值已完成，不能删除此通道"

	Tips_funding_notFoundChannelByTempId         = "未能通过临时通道id找到对应的通道: "
	Tips_funding_notFoundChannelByChannelId      = "未能通过通道id找到对应的通道: "
	Tips_funding_notFundBtcState                 = "当前通道不是处于充值btc的阶段 "
	Tips_funding_notFundAssetState               = "当前通道不是处于充值资产的阶段 "
	Tips_funding_failDecodeRawTransaction        = "DecodeRawTransaction失败 "
	Tips_funding_notEnoughBtcFundingTime         = "btc的充值必须3次"
	Tips_funding_enoughBtcFundingTime            = "btc的充值次数够3次了"
	Tips_funding_btcAmountMustGreater            = "btc的数量太少了，必须大于 "
	Tips_funding_btcTxBeenSend                   = "这个交易已经被广播过了"
	Tips_funding_fundTxIsRunning                 = "最新的btc充值正在执行，请稍后"
	Tips_funding_notFoundFundBtcTx               = "未能找到btc的充值交易"
	Tips_funding_notFoundFundAssetTx             = "未能找到资产的充值交易"
	Tips_funding_notFoundVin                     = "交易hex里面未能找到vin数据"
	Tips_funding_notFoundVout                    = "交易hex里面未能找到vout数据"
	Tips_funding_wrongBtcHexVin                  = "交易hex里面vin数据报错："
	Tips_funding_wrongFunderAddressFromBtcHex    = "此btc充值交易的输入address不是建立通道的funderAddress"
	Tips_funding_wrongChannelAddressFromBtcHex   = "此btc充值交易的输出address不是建立通道的多签地址"
	Tips_funding_wrongFunderAddressFromAssetHex  = "此资产充值交易的输入address %s 不是建立通道的funderAddress %s"
	Tips_funding_wrongChannelAddressFromAssetHex = "此资产充值交易的输出address %s 不是建立通道的多签地址 %s"

	Tips_rsmc_sendedChannel          = "通道资产数量已经变化，应该有人关闭了通道，或者广播了某次承诺交易"
	Tips_rsmc_notTargetUser          = "你不是消息的处理者 "
	Tips_rsmc_errorCommitmentTxType  = "此最新承诺交易的交易类型不匹配，应该有其他的交易流程未完成："
	Tips_rsmc_errorCommitmentTxState = "此最新承诺交易的当前状态不匹配当前的交易要求: "
	Tips_rsmc_notEnoughBalance       = "余额不足"
	Tips_rsmc_wrongPrivateKeyForLast = "传入的私钥%s和上一个交易使用的pubKey%s不匹配"
	Tips_rsmc_wrongChannelPrivateKey = "传入的通道私钥%s和通道建立时用到pubKey%s不匹配"
	Tips_rsmc_notSameValueWhenCreate = "此%s传入和刚刚创建时传入的值不一致"
	Tips_rsmc_notPairPrivAndPubKey   = "%s和%s不是一对匹配公钥私钥对"
	Tips_rsmc_notDoItAgagin          = "当前交易已经完成，不用重复处理"
	Tips_rsmc_failToCreate           = "创建 %s 失败"
	Tips_rsmc_failToGetInput         = "为签名%s而获取输入（vin）数据失败"

	Tips_htlc_expiryTimeAfterNow         = "%s必须晚于当前时间"
	Tips_htlc_noPrivatePath              = "没有找到可以使用的私有通道"
	Tips_htlc_noChanneFromRountingPacket = "从routing_packet中，未能找到合适的可用通道"
	Tips_htlc_notTheHltcSender           = "目标用户不是此htlc交易的付款方"
	Tips_htlc_wrongRForH                 = "输入的R不能创建的H匹配"
	Tips_htlc_failToGetBlockHeight       = "获取区块高度失败，请稍候重试"
	Tips_htlc_timeOut                    = "交易已经超时了，不用再发送R了"
	Tips_htlc_wrongChannelState          = "此通道当前处于htlc状态%d，非%d的可用状态"
)
