// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package proxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloProxyRequest struct {
	Sayhi                string   `protobuf:"bytes,1,opt,name=sayhi,proto3" json:"sayhi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloProxyRequest) Reset()         { *m = HelloProxyRequest{} }
func (m *HelloProxyRequest) String() string { return proto.CompactTextString(m) }
func (*HelloProxyRequest) ProtoMessage()    {}
func (*HelloProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *HelloProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloProxyRequest.Unmarshal(m, b)
}
func (m *HelloProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloProxyRequest.Marshal(b, m, deterministic)
}
func (m *HelloProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloProxyRequest.Merge(m, src)
}
func (m *HelloProxyRequest) XXX_Size() int {
	return xxx_messageInfo_HelloProxyRequest.Size(m)
}
func (m *HelloProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloProxyRequest proto.InternalMessageInfo

func (m *HelloProxyRequest) GetSayhi() string {
	if m != nil {
		return m.Sayhi
	}
	return ""
}

type HelloProxyResponse struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloProxyResponse) Reset()         { *m = HelloProxyResponse{} }
func (m *HelloProxyResponse) String() string { return proto.CompactTextString(m) }
func (*HelloProxyResponse) ProtoMessage()    {}
func (*HelloProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *HelloProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloProxyResponse.Unmarshal(m, b)
}
func (m *HelloProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloProxyResponse.Marshal(b, m, deterministic)
}
func (m *HelloProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloProxyResponse.Merge(m, src)
}
func (m *HelloProxyResponse) XXX_Size() int {
	return xxx_messageInfo_HelloProxyResponse.Size(m)
}
func (m *HelloProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloProxyResponse proto.InternalMessageInfo

func (m *HelloProxyResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloProxyRequest)(nil), "proxy.HelloProxyRequest")
	proto.RegisterType((*HelloProxyResponse)(nil), "proxy.HelloProxyResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x28, 0xca, 0xaf, 0xa8, 0x54, 0xd2, 0xe4, 0x12,
	0xf4, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x00, 0xf1, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x44, 0xb8, 0x58, 0x8b, 0x13, 0x2b, 0x33, 0x32, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20,
	0x1c, 0x25, 0x0d, 0x2e, 0x21, 0x64, 0xa5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c,
	0x2c, 0x45, 0xa9, 0xc5, 0x05, 0x50, 0xa5, 0x60, 0xb6, 0x91, 0x17, 0x17, 0x2b, 0x58, 0x91, 0x90,
	0x23, 0x17, 0x17, 0x42, 0x8b, 0x90, 0x84, 0x1e, 0xd8, 0x4e, 0x3d, 0x0c, 0x0b, 0xa5, 0x24, 0xb1,
	0xc8, 0x40, 0xcc, 0x4f, 0x62, 0x03, 0x3b, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xdd,
	0xa7, 0xe7, 0xbb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	// lncli: `helloProxy`
	//helloProxy is a `say hi` gRPC.
	HelloProxy(ctx context.Context, in *HelloProxyRequest, opts ...grpc.CallOption) (*HelloProxyResponse, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) HelloProxy(ctx context.Context, in *HelloProxyRequest, opts ...grpc.CallOption) (*HelloProxyResponse, error) {
	out := new(HelloProxyResponse)
	err := c.cc.Invoke(ctx, "/proxy.Proxy/HelloProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	// lncli: `helloProxy`
	//helloProxy is a `say hi` gRPC.
	HelloProxy(context.Context, *HelloProxyRequest) (*HelloProxyResponse, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) HelloProxy(ctx context.Context, req *HelloProxyRequest) (*HelloProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloProxy not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_HelloProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).HelloProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Proxy/HelloProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).HelloProxy(ctx, req.(*HelloProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloProxy",
			Handler:    _Proxy_HelloProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
