// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rsmc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RsmcPaymentRequest struct {
	ChannelId            string             `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Amount               float64            `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RecipientInfo        *RecipientNodeInfo `protobuf:"bytes,3,opt,name=recipientInfo,proto3" json:"recipientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RsmcPaymentRequest) Reset()         { *m = RsmcPaymentRequest{} }
func (m *RsmcPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*RsmcPaymentRequest) ProtoMessage()    {}
func (*RsmcPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fecbc7e287e63a67, []int{0}
}

func (m *RsmcPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RsmcPaymentRequest.Unmarshal(m, b)
}
func (m *RsmcPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RsmcPaymentRequest.Marshal(b, m, deterministic)
}
func (m *RsmcPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RsmcPaymentRequest.Merge(m, src)
}
func (m *RsmcPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_RsmcPaymentRequest.Size(m)
}
func (m *RsmcPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RsmcPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RsmcPaymentRequest proto.InternalMessageInfo

func (m *RsmcPaymentRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *RsmcPaymentRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RsmcPaymentRequest) GetRecipientInfo() *RecipientNodeInfo {
	if m != nil {
		return m.RecipientInfo
	}
	return nil
}

type RsmcPaymentResponse struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AmountA              float64  `protobuf:"fixed64,2,opt,name=amount_a,json=amountA,proto3" json:"amount_a,omitempty"`
	AmountB              float64  `protobuf:"fixed64,3,opt,name=amount_b,json=amountB,proto3" json:"amount_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RsmcPaymentResponse) Reset()         { *m = RsmcPaymentResponse{} }
func (m *RsmcPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*RsmcPaymentResponse) ProtoMessage()    {}
func (*RsmcPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fecbc7e287e63a67, []int{1}
}

func (m *RsmcPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RsmcPaymentResponse.Unmarshal(m, b)
}
func (m *RsmcPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RsmcPaymentResponse.Marshal(b, m, deterministic)
}
func (m *RsmcPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RsmcPaymentResponse.Merge(m, src)
}
func (m *RsmcPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_RsmcPaymentResponse.Size(m)
}
func (m *RsmcPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RsmcPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RsmcPaymentResponse proto.InternalMessageInfo

func (m *RsmcPaymentResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *RsmcPaymentResponse) GetAmountA() float64 {
	if m != nil {
		return m.AmountA
	}
	return 0
}

func (m *RsmcPaymentResponse) GetAmountB() float64 {
	if m != nil {
		return m.AmountB
	}
	return 0
}

func init() {
	proto.RegisterType((*RsmcPaymentRequest)(nil), "proxy.RsmcPaymentRequest")
	proto.RegisterType((*RsmcPaymentResponse)(nil), "proxy.RsmcPaymentResponse")
}

func init() {
	proto.RegisterFile("rsmc.proto", fileDescriptor_fecbc7e287e63a67)
}

var fileDescriptor_fecbc7e287e63a67 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2a, 0xce, 0x4d,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x28, 0xca, 0xaf, 0xa8, 0x94, 0xe2, 0x2c,
	0x2a, 0x80, 0x8a, 0x28, 0x75, 0x33, 0x72, 0x09, 0x05, 0x15, 0xe7, 0x26, 0x07, 0x24, 0x56, 0xe6,
	0xa6, 0xe6, 0x95, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x72, 0x71, 0x25, 0x67,
	0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0xc4, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71,
	0x42, 0x45, 0x3c, 0x53, 0x84, 0xc4, 0xb8, 0xd8, 0x12, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x18, 0x83, 0xa0, 0x3c, 0x21, 0x3b, 0x2e, 0xde, 0xa2, 0xd4, 0xe4, 0xcc, 0x82,
	0xcc, 0xd4, 0xbc, 0x12, 0xcf, 0xbc, 0xb4, 0x7c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x09,
	0x3d, 0xb0, 0xbd, 0x7a, 0x41, 0x30, 0x39, 0xbf, 0xfc, 0x94, 0x54, 0x90, 0x7c, 0x10, 0xaa, 0x72,
	0xa5, 0x2c, 0x2e, 0x61, 0x14, 0xc7, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x12, 0x72, 0x8d, 0x24,
	0x17, 0x07, 0xc4, 0xfe, 0xf8, 0x44, 0xa8, 0x7b, 0xd8, 0x21, 0x7c, 0x47, 0x24, 0xa9, 0x24, 0xb0,
	0x5b, 0xe0, 0x52, 0x4e, 0x46, 0x3e, 0x5c, 0x2c, 0x20, 0xbb, 0x84, 0x5c, 0xb8, 0xb8, 0x91, 0xec,
	0x14, 0x92, 0x84, 0xb9, 0x15, 0x23, 0x50, 0xa4, 0xa4, 0xb0, 0x49, 0x41, 0x9c, 0xe8, 0xc4, 0x12,
	0xc5, 0x54, 0x90, 0x94, 0xc4, 0x06, 0x0e, 0x54, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab,
	0x87, 0xf7, 0xc6, 0x74, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RsmcClient is the client API for Rsmc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RsmcClient interface {
	RsmcPayment(ctx context.Context, in *RsmcPaymentRequest, opts ...grpc.CallOption) (*RsmcPaymentResponse, error)
}

type rsmcClient struct {
	cc grpc.ClientConnInterface
}

func NewRsmcClient(cc grpc.ClientConnInterface) RsmcClient {
	return &rsmcClient{cc}
}

func (c *rsmcClient) RsmcPayment(ctx context.Context, in *RsmcPaymentRequest, opts ...grpc.CallOption) (*RsmcPaymentResponse, error) {
	out := new(RsmcPaymentResponse)
	err := c.cc.Invoke(ctx, "/proxy.Rsmc/RsmcPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RsmcServer is the server API for Rsmc service.
type RsmcServer interface {
	RsmcPayment(context.Context, *RsmcPaymentRequest) (*RsmcPaymentResponse, error)
}

// UnimplementedRsmcServer can be embedded to have forward compatible implementations.
type UnimplementedRsmcServer struct {
}

func (*UnimplementedRsmcServer) RsmcPayment(ctx context.Context, req *RsmcPaymentRequest) (*RsmcPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsmcPayment not implemented")
}

func RegisterRsmcServer(s *grpc.Server, srv RsmcServer) {
	s.RegisterService(&_Rsmc_serviceDesc, srv)
}

func _Rsmc_RsmcPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsmcPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsmcServer).RsmcPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Rsmc/RsmcPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsmcServer).RsmcPayment(ctx, req.(*RsmcPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rsmc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Rsmc",
	HandlerType: (*RsmcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RsmcPayment",
			Handler:    _Rsmc_RsmcPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsmc.proto",
}
