// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Mnemonic             string   `protobuf:"bytes,1,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	LoginToken           string   `protobuf:"bytes,2,opt,name=login_token,json=loginToken,proto3" json:"login_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

func (m *LoginRequest) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

type LoginResponse struct {
	UserPeerId           string   `protobuf:"bytes,1,opt,name=user_peerId,json=userPeerId,proto3" json:"user_peerId,omitempty"`
	NodePeerId           string   `protobuf:"bytes,2,opt,name=node_peerId,json=nodePeerId,proto3" json:"node_peerId,omitempty"`
	NodeAddress          string   `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	HtlcFeeRate          float64  `protobuf:"fixed64,4,opt,name=htlc_fee_rate,json=htlcFeeRate,proto3" json:"htlc_fee_rate,omitempty"`
	HtlcMaxFee           float64  `protobuf:"fixed64,5,opt,name=htlc_max_fee,json=htlcMaxFee,proto3" json:"htlc_max_fee,omitempty"`
	ChainNodeType        string   `protobuf:"bytes,6,opt,name=chain_node_type,json=chainNodeType,proto3" json:"chain_node_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUserPeerId() string {
	if m != nil {
		return m.UserPeerId
	}
	return ""
}

func (m *LoginResponse) GetNodePeerId() string {
	if m != nil {
		return m.NodePeerId
	}
	return ""
}

func (m *LoginResponse) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *LoginResponse) GetHtlcFeeRate() float64 {
	if m != nil {
		return m.HtlcFeeRate
	}
	return 0
}

func (m *LoginResponse) GetHtlcMaxFee() float64 {
	if m != nil {
		return m.HtlcMaxFee
	}
	return 0
}

func (m *LoginResponse) GetChainNodeType() string {
	if m != nil {
		return m.ChainNodeType
	}
	return ""
}

type ChangePasswordRequest struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{5}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "proxy.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proxy.LoginResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "proxy.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "proxy.ChangePasswordResponse")
	proto.RegisterType((*LogoutRequest)(nil), "proxy.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "proxy.LogoutResponse")
}

func init() {
	proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f)
}

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x80, 0x49, 0xdd, 0x06, 0x3d, 0x9b, 0x6e, 0x97, 0xd1, 0x5d, 0x42, 0x50, 0xac, 0xb9, 0x90,
	0x7a, 0x53, 0xa4, 0xe2, 0x03, 0xa8, 0x50, 0x10, 0xad, 0x94, 0x50, 0x10, 0xbc, 0x09, 0xd3, 0xe4,
	0xd8, 0x16, 0xd3, 0x99, 0x71, 0x66, 0x42, 0xda, 0xd7, 0xf3, 0x51, 0x7c, 0x12, 0x99, 0x93, 0x89,
	0xfd, 0x41, 0x2f, 0xf3, 0xcd, 0x77, 0x7e, 0x73, 0x20, 0x6a, 0x78, 0x55, 0xa1, 0x9d, 0x28, 0x2d,
	0xad, 0x64, 0x7d, 0xa5, 0xe5, 0xfe, 0x90, 0x7e, 0x82, 0xe8, 0xb3, 0x5c, 0x6f, 0x45, 0x86, 0x3f,
	0x6b, 0x34, 0x96, 0x25, 0xf0, 0x70, 0x27, 0x70, 0x27, 0xc5, 0xb6, 0x88, 0x83, 0x51, 0x30, 0x7e,
	0x94, 0xfd, 0xfd, 0x66, 0xcf, 0xe1, 0xba, 0x72, 0x6e, 0x6e, 0xe5, 0x0f, 0x14, 0x71, 0x8f, 0x9e,
	0x81, 0xd0, 0xd2, 0x91, 0xf4, 0x77, 0x00, 0x03, 0x9f, 0xcd, 0x28, 0x29, 0x0c, 0xba, 0x90, 0xda,
	0xa0, 0xce, 0x15, 0xa2, 0xfe, 0x58, 0xfa, 0x8c, 0xe0, 0xd0, 0x82, 0x88, 0x13, 0x84, 0x2c, 0xb1,
	0x13, 0x7c, 0x4e, 0x87, 0xbc, 0xf0, 0x02, 0x22, 0x12, 0x78, 0x59, 0x6a, 0x34, 0x26, 0x7e, 0x40,
	0x06, 0x05, 0xbd, 0x6b, 0x11, 0x4b, 0x61, 0xb0, 0xb1, 0x55, 0x91, 0x7f, 0x47, 0xcc, 0x35, 0xb7,
	0x18, 0x5f, 0x8d, 0x82, 0x71, 0x90, 0x5d, 0x3b, 0x38, 0x43, 0xcc, 0xb8, 0x45, 0x36, 0x82, 0x88,
	0x9c, 0x1d, 0xdf, 0x3b, 0x2f, 0xee, 0x93, 0x02, 0x8e, 0xcd, 0xf9, 0x7e, 0x86, 0xc8, 0x5e, 0xc2,
	0xb0, 0xd8, 0xf0, 0xad, 0xc8, 0xa9, 0x9c, 0x3d, 0x28, 0x8c, 0x43, 0xaa, 0x35, 0x20, 0xfc, 0x45,
	0x96, 0xb8, 0x3c, 0x28, 0x4c, 0x11, 0xee, 0x3e, 0x6c, 0xb8, 0x58, 0xe3, 0x82, 0x1b, 0xd3, 0x48,
	0x5d, 0x76, 0xab, 0x7b, 0x05, 0xb7, 0x45, 0xad, 0x35, 0x0a, 0x9b, 0x2b, 0xff, 0xe4, 0x07, 0x1e,
	0x7a, 0xde, 0x45, 0xd0, 0x50, 0xd8, 0x1c, 0xb5, 0x9e, 0x1f, 0x0a, 0x9b, 0x4e, 0x49, 0x5f, 0xc3,
	0xfd, 0x65, 0x19, 0xbf, 0xd3, 0x7b, 0x08, 0x35, 0x9a, 0xba, 0xb2, 0x3e, 0xbb, 0xff, 0x4a, 0x87,
	0xb4, 0x7c, 0x59, 0x5b, 0xdf, 0x50, 0x7a, 0x0b, 0x37, 0x1d, 0x68, 0x43, 0xa7, 0xbf, 0x02, 0x08,
	0xbf, 0xd2, 0x15, 0xb0, 0x29, 0xf4, 0xe9, 0x57, 0xb1, 0xc7, 0x13, 0xba, 0x84, 0xc9, 0xe9, 0x19,
	0x24, 0x4f, 0xce, 0xa1, 0xaf, 0x3c, 0x87, 0x9b, 0xf3, 0x9e, 0xd8, 0x53, 0xef, 0xfd, 0x73, 0x23,
	0xc9, 0xb3, 0xff, 0xbc, 0xfa, 0x74, 0x6f, 0x21, 0x6c, 0xfb, 0x63, 0x27, 0xe5, 0x8e, 0xfd, 0x27,
	0x77, 0x17, 0xb4, 0x0d, 0x7b, 0x7f, 0xf5, 0xad, 0xa7, 0x56, 0xab, 0x90, 0xce, 0xf8, 0xcd, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xdd, 0x2f, 0xb5, 0xd6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proxy.Wallet/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/proxy.Wallet/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/proxy.Wallet/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedWalletServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedWalletServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Wallet/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Wallet/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Wallet/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Wallet_Login_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Wallet_ChangePassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Wallet_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
